package main

// Cottage-garden flowers: the annuals and perennials most gardeners meet first.
func init() {
	register(
		&Species{
			ID: "sunflower", Common: "Sunflower", Latin: "Helianthus annuus",
			Family: "Asteraceae", Kind: KindFlower, Rarity: Common,
			Origin: "North America", Bloom: "midsummer to early autumn",
			Sun: "full sun", Water: "moderate, deep drinks", Height: "1.5–3 m",
			Note:    "Sow where it will stand: the taproot hates being moved.",
			Desc:    "A fast, towering annual whose flower head is really hundreds of tiny florets packed into a spiral. Young heads track the sun across the sky; mature ones settle facing east. The seeds feed finches all autumn if you leave the heads standing.",
			Seasons: []Season{Spring, Summer}, SeedCost: 3, Unlock: 0, Hours: 17,
			Palette: Palette{Stem: "64", Leaf: "70", Bloom: "220", Accent: "130"},
			Glyphs:  map[rune]glyphClass{'@': clAccent},
			Art: [StageCount][]string{
				{"  ˙  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{"  ◍  ", " ε│з ", "  │  "},
				{" ❀❀❀ ", " ❀@❀ ", " ❀❀❀ ", "ϑ╲│╱ϑ", "  │  "},
			},
		},
		&Species{
			ID: "foxglove", Common: "Common Foxglove", Latin: "Digitalis purpurea",
			Family: "Plantaginaceae", Kind: KindFlower, Rarity: Uncommon,
			Origin: "western Europe", Bloom: "early to midsummer",
			Sun: "light shade", Water: "evenly moist", Height: "1–2 m",
			Note:    "Every part is poisonous — a beautiful plant to look at, never to taste.",
			Desc:    "A biennial that spends its first year as a flat rosette and its second throwing up a one-sided spire of speckled thimbles. Bumblebees crawl bodily inside each bell. The heart drug digoxin was first isolated from its leaves.",
			Seasons: []Season{Spring, Summer}, SeedCost: 5, Unlock: 2, Hours: 19,
			Palette: Palette{Stem: "65", Leaf: "71", Bloom: "176", Accent: "182"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ζ│ζ ", "  │  "},
				{"  ◦  ", " ◦│◦ ", " ζ│ζ "},
				{"  ✿  ", " ✿│✿ ", " ✿│✿ ", " ✿│✿ ", " ζ│ζ "},
			},
		},
		&Species{
			ID: "marigold", Common: "French Marigold", Latin: "Tagetes patula",
			Family: "Asteraceae", Kind: KindFlower, Rarity: Common,
			Origin: "Mexico and Guatemala", Bloom: "early summer to first frost",
			Sun: "full sun", Water: "moderate", Height: "20–40 cm",
			Note:    "Traditionally planted beside tomatoes; the roots discourage root-knot nematodes.",
			Desc:    "A stocky annual with pungent, ferny foliage and velvety orange-and-mahogany heads that keep coming as long as you deadhead them. Despite the name it is Mexican, carried to European gardens via French seed traders.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 2, Unlock: 0, Hours: 13,
			Palette: Palette{Stem: "65", Leaf: "71", Bloom: "208", Accent: "166"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ζζζ ", "  │  "},
				{" ◦ ◦ ", " ζ│ζ ", "  │  "},
				{" ❁ ❁ ", "ζ╲│╱ζ", " ζ│ζ ", "  │  "},
			},
		},
		&Species{
			ID: "zinnia", Common: "Zinnia", Latin: "Zinnia elegans",
			Family: "Asteraceae", Kind: KindFlower, Rarity: Common,
			Origin: "Mexico", Bloom: "midsummer to frost",
			Sun: "full sun", Water: "moderate, water at the roots", Height: "30–90 cm",
			Note:    "Cut them hard for the vase — each stem taken brings three more.",
			Desc:    "A heat-loving annual in every colour but true blue, with stiff stems that make it a florist's favourite. Butterflies work the flat, landing-pad heads all day. Keep water off the leaves and mildew stays away.",
			Seasons: []Season{Summer}, SeedCost: 3, Unlock: 0, Hours: 15,
			Palette: Palette{Stem: "71", Leaf: "77", Bloom: "205", Accent: "220"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{"  ◦  ", " ε│з ", "  │  "},
				{" ✿ ✿ ", " ╲│╱ ", " ε│з ", "  │  "},
			},
		},
		&Species{
			ID: "cosmos", Common: "Cosmos", Latin: "Cosmos bipinnatus",
			Family: "Asteraceae", Kind: KindFlower, Rarity: Common,
			Origin: "Mexico", Bloom: "midsummer to autumn",
			Sun: "full sun", Water: "low once settled", Height: "0.9–1.5 m",
			Note:    "Poor soil gives more flowers; rich soil gives a jungle of leaves.",
			Desc:    "An airy annual with thread-fine foliage and single saucer flowers held on wiry stems that sway at the slightest breeze. Self-sows generously. The name comes from the Greek kosmos, for order and harmony.",
			Seasons: []Season{Summer, Autumn}, SeedCost: 3, Unlock: 0, Hours: 15,
			Palette: Palette{Stem: "72", Leaf: "79", Bloom: "218", Accent: "222"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ~  "},
				{" ~│~ ", "  │  "},
				{" ◦ ◦ ", " ~│~ ", "  │  "},
				{"✿  ✿ ", " ╲╱  ", " ~│~ ", "  │  "},
			},
		},
		&Species{
			ID: "snapdragon", Common: "Snapdragon", Latin: "Antirrhinum majus",
			Family: "Plantaginaceae", Kind: KindFlower, Rarity: Common,
			Origin: "Mediterranean", Bloom: "late spring through summer",
			Sun: "full sun to light shade", Water: "moderate", Height: "30–90 cm",
			Note:    "Pinch the young tips once and you get twice the spikes.",
			Desc:    "A short-lived perennial grown as an annual, named for the hinged flower that opens like a jaw when squeezed. Only bees heavy enough to force the lip get at the nectar. Dried seed pods look uncannily like tiny skulls.",
			Seasons: []Season{Spring, Summer}, SeedCost: 3, Unlock: 1, Hours: 16,
			Palette: Palette{Stem: "65", Leaf: "72", Bloom: "211", Accent: "217"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{"  ◦  ", " ◦│◦ ", " ε│з "},
				{"  ❁  ", " ❁│❁ ", " ❁│❁ ", " ε│з ", "  │  "},
			},
		},
		&Species{
			ID: "poppy", Common: "Corn Poppy", Latin: "Papaver rhoeas",
			Family: "Papaveraceae", Kind: KindFlower, Rarity: Common,
			Origin: "Europe and North Africa", Bloom: "late spring to midsummer",
			Sun: "full sun", Water: "low", Height: "30–70 cm",
			Note:    "Scatter the seed on bare, disturbed ground and never transplant it.",
			Desc:    "The scarlet field poppy of ploughed land and roadside verges, whose seed can wait decades in the soil for someone to turn it over. Each crumpled flower lasts a day or two; the pepper-pot capsule that follows scatters thousands of seeds.",
			Seasons: []Season{Spring, Summer}, SeedCost: 3, Unlock: 1, Hours: 14,
			Palette: Palette{Stem: "65", Leaf: "71", Bloom: "196", Accent: "232"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ζ│ζ ", "  │  "},
				{"  ◍  ", "  │  ", " ζ│ζ "},
				{"  ❀  ", "  │  ", " ζ│ζ ", "  │  "},
			},
		},
		&Species{
			ID: "coneflower", Common: "Purple Coneflower", Latin: "Echinacea purpurea",
			Family: "Asteraceae", Kind: KindFlower, Rarity: Common,
			Origin: "eastern North American prairies", Bloom: "midsummer to early autumn",
			Sun: "full sun", Water: "low once established", Height: "60–120 cm",
			Note:    "Leave the seed heads up all winter — goldfinches will thank you.",
			Desc:    "A tough prairie perennial with drooping mauve rays around a bristling copper cone. The genus name comes from the Greek echinos, hedgehog, for that spiny centre. Long used by Plains peoples as a medicinal root.",
			Seasons: []Season{Summer, Autumn}, SeedCost: 4, Unlock: 2, Hours: 17,
			Palette: Palette{Stem: "65", Leaf: "71", Bloom: "176", Accent: "166"},
			Glyphs:  map[rune]glyphClass{'▲': clAccent},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{"  ◍  ", " ε│з ", "  │  "},
				{"  ▲  ", " ✽▲✽ ", " ╲│╱ ", " ε│з ", "  │  "},
			},
		},
		&Species{
			ID: "rudbeckia", Common: "Black-eyed Susan", Latin: "Rudbeckia hirta",
			Family: "Asteraceae", Kind: KindFlower, Rarity: Common,
			Origin: "central and eastern North America", Bloom: "midsummer to autumn",
			Sun: "full sun", Water: "moderate", Height: "40–90 cm",
			Note:    "Short-lived, but it self-sows into any gap you leave for it.",
			Desc:    "A bristly-leaved prairie daisy with gold rays around a chocolate-brown dome. It colonises roadsides and old fields, and to a bee's ultraviolet eyes the petals carry a dark bullseye guiding it to the centre.",
			Seasons: []Season{Summer, Autumn}, SeedCost: 3, Unlock: 1, Hours: 16,
			Palette: Palette{Stem: "64", Leaf: "70", Bloom: "214", Accent: "94"},
			Glyphs:  map[rune]glyphClass{'●': clAccent},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{"  ◦  ", " ε│з ", "  │  "},
				{" ✽●✽ ", " ╲│╱ ", " ε│з ", "  │  "},
			},
		},
		&Species{
			ID: "lupine", Common: "Garden Lupine", Latin: "Lupinus polyphyllus",
			Family: "Fabaceae", Kind: KindFlower, Rarity: Uncommon,
			Origin: "western North America", Bloom: "late spring to midsummer",
			Sun: "full sun", Water: "moderate", Height: "0.9–1.5 m",
			Note:    "Nick the hard seed coat and soak overnight before sowing.",
			Desc:    "A pea-family perennial with palmate leaves that hold raindrops like mercury and dense spires of hooded flowers. Root nodules fix nitrogen, so lupines quietly feed the soil around them.",
			Seasons: []Season{Spring, Summer}, SeedCost: 5, Unlock: 3, Hours: 18,
			Palette: Palette{Stem: "65", Leaf: "72", Bloom: "99", Accent: "141"},
			Art: [StageCount][]string{
				{"  ●  "},
				{"  ϑ  "},
				{" ╲│╱ ", "  │  "},
				{"  ◦  ", " ◦│◦ ", " ╲│╱ "},
				{"  ❋  ", " ❋│❋ ", " ❋│❋ ", " ╲│╱ ", "  │  "},
			},
		},
		&Species{
			ID: "delphinium", Common: "Delphinium", Latin: "Delphinium elatum",
			Family: "Ranunculaceae", Kind: KindFlower, Rarity: Rare,
			Origin: "mountains of Europe and Asia", Bloom: "early and late summer",
			Sun: "full sun, sheltered", Water: "generous, never waterlogged", Height: "1.2–2 m",
			Note:    "Stake early — one summer storm can flatten an unsupported spire.",
			Desc:    "The great blue spire of the border, named for the dolphin-shaped bud. Cut the first flush down and a second, shorter set of spikes usually follows in late summer. Slugs adore the emerging shoots.",
			Seasons: []Season{Spring, Summer}, SeedCost: 9, Unlock: 8, Hours: 19,
			Palette: Palette{Stem: "65", Leaf: "71", Bloom: "63", Accent: "111"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ζ│ζ ", "  │  "},
				{"  ◦  ", " ◦│◦ ", " ζ│ζ "},
				{"  ❋  ", " ❋│❋ ", " ❋│❋ ", " ❋│❋ ", " ζ│ζ "},
			},
		},
		&Species{
			ID: "peony", Common: "Chinese Peony", Latin: "Paeonia lactiflora",
			Family: "Paeoniaceae", Kind: KindFlower, Rarity: Rare,
			Origin: "northern China, Siberia, Mongolia", Bloom: "late spring",
			Sun: "full sun", Water: "moderate, deep", Height: "60–100 cm",
			Note:    "Plant the crown barely 3 cm deep; any deeper and it sulks without flowering.",
			Desc:    "A long-lived perennial that outlives the gardener who plants it, with fat buds opening into bowls of ruffled petals. Ants patrol the buds for their sugary nectar and do the plant no harm at all.",
			Seasons: []Season{Spring}, SeedCost: 10, Unlock: 10, Hours: 20,
			Palette: Palette{Stem: "65", Leaf: "71", Bloom: "218", Accent: "175"},
			Art: [StageCount][]string{
				{"  ●  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" ◍ ◍ ", " ε│з ", "  │  "},
				{" ❀ ❀ ", "ε╲│╱з", " ε│з ", "  │  "},
			},
		},
		&Species{
			ID: "rose", Common: "Apothecary's Rose", Latin: "Rosa gallica",
			Family: "Rosaceae", Kind: KindFlower, Rarity: Rare,
			Origin: "southern and central Europe", Bloom: "early summer, once",
			Sun: "full sun", Water: "moderate, deep soakings", Height: "1–1.5 m",
			Note:    "Prune just above an outward-facing bud to keep the middle open.",
			Desc:    "One of the oldest roses in cultivation, grown in medieval monastery gardens for its scent, which strengthens rather than fades when the petals are dried. Hips follow the single midsummer flush and glow scarlet into winter.",
			Seasons: []Season{Spring, Summer}, SeedCost: 11, Unlock: 12, Hours: 20,
			Palette: Palette{Stem: "58", Leaf: "71", Bloom: "161", Accent: "196"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" ◦ ◦ ", " ε│з ", "  │  "},
				{" ❀ ❀ ", "ε╲│╱з", " ❀│❀ ", "ε╲│╱з", "  │  "},
			},
		},
		&Species{
			ID: "dahlia", Common: "Dahlia", Latin: "Dahlia pinnata",
			Family: "Asteraceae", Kind: KindFlower, Rarity: Rare,
			Origin: "highlands of Mexico", Bloom: "midsummer until frost",
			Sun: "full sun", Water: "thirsty in summer", Height: "0.6–1.5 m",
			Note:    "Lift the tubers before hard frost unless your winters stay mild.",
			Desc:    "Grown from tubers, the dahlia is the national flower of Mexico and was first cultivated there for food rather than show. Breeders have pushed it into dozens of forms, from single daisies to cactus heads the size of a dinner plate.",
			Seasons: []Season{Summer, Autumn}, SeedCost: 9, Unlock: 9, Hours: 19,
			Palette: Palette{Stem: "65", Leaf: "71", Bloom: "197", Accent: "212"},
			Art: [StageCount][]string{
				{"  ●  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{"  ◍  ", " ε│з ", "  │  "},
				{" ✺✺✺ ", " ✺❉✺ ", " ╲│╱ ", " ε│з ", "  │  "},
			},
		},
		&Species{
			ID: "chrysanthemum", Common: "Florist's Chrysanthemum", Latin: "Chrysanthemum morifolium",
			Family: "Asteraceae", Kind: KindFlower, Rarity: Uncommon,
			Origin: "China", Bloom: "autumn",
			Sun: "full sun", Water: "even moisture", Height: "45–90 cm",
			Note:    "It sets bud as the nights lengthen — keep it away from porch lights.",
			Desc:    "Cultivated in China for over two thousand years and a symbol of autumn across East Asia, where it features on the Japanese imperial seal. Pinching the shoots until midsummer turns one stem into a dome of late colour.",
			Seasons: []Season{Autumn}, SeedCost: 6, Unlock: 4, Hours: 17,
			Palette: Palette{Stem: "65", Leaf: "71", Bloom: "179", Accent: "215"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ζ│ζ ", "  │  "},
				{" ◦ ◦ ", " ζ│ζ ", "  │  "},
				{"❁ ❁ ❁", " ╲│╱ ", " ζ│ζ ", "  │  "},
			},
		},
		&Species{
			ID: "bleedingheart", Common: "Bleeding Heart", Latin: "Lamprocapnos spectabilis",
			Family: "Papaveraceae", Kind: KindFlower, Rarity: Rare,
			Origin: "Siberia, northern China, Korea, Japan", Bloom: "mid to late spring",
			Sun: "dappled shade", Water: "consistently moist", Height: "60–90 cm",
			Note:    "It dies back by midsummer — plant ferns beside it to cover the gap.",
			Desc:    "An arching woodland perennial hung with rows of pink lockets, each with a white droplet at the tip. Long known as Dicentra spectabilis, it was moved to its own genus once DNA work showed how distinct it was.",
			Seasons: []Season{Spring}, SeedCost: 10, Unlock: 11, Hours: 19,
			Palette: Palette{Stem: "71", Leaf: "77", Bloom: "211", Accent: "255"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" ╭──╮", " ◦ ◦ ", " ε│з "},
				{" ╭───╮", " ♥ ♥ ♥", " ε╲│╱з", "   │  "},
			},
		},
	)
}
