package main

// Trees and shrubs. In a garden this small they stay politely miniature.
func init() {
	register(
		&Species{
			ID: "japanesemaple", Common: "Japanese Maple", Latin: "Acer palmatum",
			Family: "Sapindaceae", Kind: KindTree, Rarity: Rare,
			Origin: "Japan, Korea, China", Bloom: "small red flowers in spring",
			Sun: "dappled shade; scorches in hot sun", Water: "even moisture", Height: "3–8 m",
			Note:    "Shelter it from wind — the fine leaf edges brown in a dry gust.",
			Desc:    "Grown in Japan for centuries and selected into hundreds of named forms, from thread-leaf weepers to upright trees. Autumn colour depends on cool nights and bright days; the winged seeds spin like helicopters.",
			Seasons: []Season{Spring, Autumn}, SeedCost: 12, Unlock: 14, Hours: 20,
			Palette: Palette{Stem: "95", Leaf: "167", Bloom: "160", Accent: "180"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ψ│ψ ", "  │  "},
				{" ψψψ ", " ╲│╱ ", "  │  "},
				{" ψψψψψ", "ψψψψψψ", " ╲ │ ╱", "   │  "},
			},
		},
		&Species{
			ID: "silverbirch", Common: "Silver Birch", Latin: "Betula pendula",
			Family: "Betulaceae", Kind: KindTree, Rarity: Uncommon,
			Origin: "Europe and western Asia", Bloom: "catkins in early spring",
			Sun: "full sun", Water: "moderate", Height: "15–25 m",
			Note:    "Never prune it in spring; birches bleed sap heavily.",
			Desc:    "A pioneer tree that colonises bare ground fast and lives fast too, rarely passing a century. The white bark peels in papery sheets and is waterproof enough that it was once used for roofing and canoes.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 8, Unlock: 8, Hours: 19,
			Palette: Palette{Stem: "252", Leaf: "113", Bloom: "179", Accent: "240"},
			Glyphs:  map[rune]glyphClass{'▪': clAccent},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" εзε ", " ╲│╱ ", "  │  "},
				{" εзεзε", " ╲ │ ╱", "   │  ", "  ▪│  ", "   │▪ "},
			},
		},
		&Species{
			ID: "ginkgo", Common: "Ginkgo", Latin: "Ginkgo biloba",
			Family: "Ginkgoaceae", Kind: KindTree, Rarity: Legendary,
			Origin: "China", Bloom: "no true flowers; it predates them",
			Sun: "full sun", Water: "moderate", Height: "20–35 m",
			Note:    "Plant a male tree unless you can forgive the smell of the fallen seed.",
			Desc:    "A living fossil with no close living relatives, effectively unchanged for some 200 million years. Its fan-shaped leaves turn uniform gold and drop almost all at once. Several ginkgos survived the Hiroshima blast and are alive today.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 20, Unlock: 30, Hours: 20,
			Palette: Palette{Stem: "101", Leaf: "185", Bloom: "228", Accent: "220"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ψ  "},
				{" ψ│ψ ", "  │  "},
				{" ψψψ ", " ╲│╱ ", "  │  "},
				{" ψψψψ ", "ψψψψψψ", " ╲ │ ╱", "   │  "},
			},
		},
		&Species{
			ID: "olive", Common: "Olive", Latin: "Olea europaea",
			Family: "Oleaceae", Kind: KindTree, Rarity: Rare,
			Origin: "the Mediterranean basin", Bloom: "tiny cream flowers in late spring",
			Sun: "full sun", Water: "low; drought is its natural state", Height: "4–8 m",
			Note:    "It needs a genuinely cool winter spell before it will set fruit.",
			Desc:    "Cultivated for at least six thousand years, with individual trees in the Mediterranean known to be over two thousand years old. The silvery underside of each leaf reflects heat and holds moisture in.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 13, Unlock: 16, Hours: 20,
			Palette: Palette{Stem: "101", Leaf: "108", Bloom: "255", Accent: "60"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" εзε ", " ╲│╱ ", "  │  "},
				{" εзεзε ", "ε ● ● ε", " ╲ │ ╱ ", "   │   "},
			},
		},
		&Species{
			ID: "cherryblossom", Common: "Japanese Cherry", Latin: "Prunus serrulata",
			Family: "Rosaceae", Kind: KindTree, Rarity: Legendary,
			Origin: "Japan, Korea, China", Bloom: "a single week in spring",
			Sun: "full sun", Water: "moderate", Height: "5–12 m",
			Note:    "Prune only in summer — winter cuts invite silver leaf disease.",
			Desc:    "The tree of hanami, the Japanese custom of gathering under the blossom precisely because it lasts only days. Most ornamental cultivars are sterile and set no fruit, putting everything into flower.",
			Seasons: []Season{Spring}, SeedCost: 18, Unlock: 26, Hours: 20,
			Palette: Palette{Stem: "95", Leaf: "108", Bloom: "218", Accent: "255"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" ◦◦◦ ", " ╲│╱ ", "  │  "},
				{" ❀❀❀❀ ", "❀❀❀❀❀❀", " ╲ │ ╱", "   │  "},
			},
		},
		&Species{
			ID: "blackpine", Common: "Japanese Black Pine", Latin: "Pinus thunbergii",
			Family: "Pinaceae", Kind: KindTree, Rarity: Rare,
			Origin: "coastal Japan and South Korea", Bloom: "cones, not flowers",
			Sun: "full sun", Water: "low", Height: "2–25 m, or 30 cm as bonsai",
			Note:    "Pinch the spring candles by half to keep the needles short and dense.",
			Desc:    "The classic bonsai pine, tough enough for salt wind and poor sand, which is why it lines the Japanese coast. Left alone it becomes a craggy, asymmetric tree; trained, it holds any shape for decades.",
			Seasons: []Season{Spring, Summer, Autumn, Winter}, SeedCost: 12, Unlock: 15, Hours: 20,
			Palette: Palette{Stem: "95", Leaf: "65", Bloom: "101", Accent: "137"},
			Glyphs:  map[rune]glyphClass{'▲': clLeaf},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ▲  "},
				{"  ▲  ", "  │  "},
				{" ▲▲▲ ", "  │  ", "  │  "},
				{"  ▲  ", " ▲▲▲ ", "▲▲▲▲▲", " ╲│╱ ", "  │  "},
			},
		},
		&Species{
			ID: "apple", Common: "Apple", Latin: "Malus domestica",
			Family: "Rosaceae", Kind: KindTree, Rarity: Uncommon,
			Origin: "the Tian Shan mountains of Kazakhstan", Bloom: "pink-white blossom in spring",
			Sun: "full sun", Water: "moderate", Height: "2–8 m depending on rootstock",
			Note:    "Most varieties need a second tree nearby to pollinate them.",
			Desc:    "Every named variety is a clone kept going by grafting: an apple grown from a pip is a genetic lottery and rarely resembles its parent. Wild ancestors still grow in the forests of Kazakhstan.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 9, Unlock: 10, Hours: 20,
			Palette: Palette{Stem: "95", Leaf: "71", Bloom: "218", Accent: "196"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" ε❀з ", " ╲│╱ ", "  │  "},
				{" εзεзε ", "ε ● ● ε", " ╲ │ ╱ ", "   │   "},
			},
		},
		&Species{
			ID: "lemon", Common: "Lemon", Latin: "Citrus × limon",
			Family: "Rutaceae", Kind: KindTree, Rarity: Rare,
			Origin: "a hybrid from south Asia", Bloom: "scented white flowers, on and off all year",
			Sun: "full sun", Water: "let the top few centimetres dry out", Height: "3–6 m",
			Note:    "It can carry flowers and ripe fruit at the same time — do not panic-pick.",
			Desc:    "A natural hybrid of citron and sour orange, carried west along trade routes and grown in pots in northern Europe since the Renaissance orangery. The oil in the peel is held in visible glands you can burst with a thumbnail.",
			Seasons: []Season{Spring, Summer, Autumn, Winter}, SeedCost: 12, Unlock: 14, Hours: 20,
			Palette: Palette{Stem: "101", Leaf: "71", Bloom: "255", Accent: "226"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" ε❀з ", " ╲│╱ ", "  │  "},
				{" εзεзε ", "ε ● ● ε", " ╲ │ ╱ ", "   │   "},
			},
		},
		&Species{
			ID: "hydrangea", Common: "Bigleaf Hydrangea", Latin: "Hydrangea macrophylla",
			Family: "Hydrangeaceae", Kind: KindTree, Rarity: Uncommon,
			Origin: "Japan", Bloom: "midsummer to autumn",
			Sun: "morning sun, afternoon shade", Water: "thirsty — the name means water vessel", Height: "1–2 m",
			Note:    "Leave last year's dead heads on until spring; they protect the new buds.",
			Desc:    "Famous for changing colour with soil chemistry: acid soil frees up aluminium and the flowers turn blue, while alkaline soil keeps them pink. The showy parts are sterile bracts around tiny true flowers.",
			Seasons: []Season{Summer, Autumn}, SeedCost: 7, Unlock: 6, Hours: 19,
			Palette: Palette{Stem: "65", Leaf: "71", Bloom: "111", Accent: "176"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" ◦◦◦ ", " ε│з ", "  │  "},
				{" ❋❋ ❋❋", " ❋❋ ❋❋", " ε╲│╱з", "   │  "},
			},
		},
		&Species{
			ID: "magnolia", Common: "Saucer Magnolia", Latin: "Magnolia × soulangeana",
			Family: "Magnoliaceae", Kind: KindTree, Rarity: Rare,
			Origin: "raised near Paris from Chinese parents", Bloom: "early spring, before the leaves",
			Sun: "full sun, sheltered", Water: "moderate", Height: "6–9 m",
			Note:    "Site it away from morning sun: a frosted bud thaws too fast and browns.",
			Desc:    "Magnolias are older than bees, and their tough flowers evolved to be pollinated by beetles clambering over them. This hybrid opens fat goblets on bare branches while the rest of the garden is still asleep.",
			Seasons: []Season{Spring}, SeedCost: 15, Unlock: 20, Hours: 20,
			Palette: Palette{Stem: "95", Leaf: "71", Bloom: "218", Accent: "255"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" ◍ ◍ ", " ╲│╱ ", "  │  "},
				{" ❀  ❀ ", "❀ ❀ ❀ ", " ╲ │ ╱", "   │  "},
			},
		},
		&Species{
			ID: "willow", Common: "Weeping Willow", Latin: "Salix babylonica",
			Family: "Salicaceae", Kind: KindTree, Rarity: Rare,
			Origin: "northern China", Bloom: "catkins in spring",
			Sun: "full sun", Water: "as much as it can get", Height: "10–20 m",
			Note:    "Keep it well away from drains — willow roots will find and fill them.",
			Desc:    "A waterside tree whose bark contains salicin, the compound that led chemists to aspirin. A cut branch pushed into damp ground will usually root and become a tree of its own.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 11, Unlock: 13, Hours: 20,
			Palette: Palette{Stem: "101", Leaf: "107", Bloom: "185", Accent: "144"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ζ│ζ ", "  │  "},
				{" ζζζ ", " ╲│╱ ", "  │  "},
				{" ╭───╮", " ζ ζ ζ", " ζ │ ζ", "   │  "},
			},
		},
	)
}
