package main

// Ferns, mosses, grasses, the carnivores and the water garden — the corners
// of the plot that do not look like anything else.
func init() {
	register(
		&Species{
			ID: "maidenhair", Common: "Maidenhair Fern", Latin: "Adiantum capillus-veneris",
			Family: "Pteridaceae", Kind: KindFern, Rarity: Uncommon,
			Origin: "warm temperate regions worldwide", Bloom: "none; it reproduces by spore",
			Sun: "shade", Water: "constantly humid", Height: "20–40 cm",
			Note:    "Dry air browns it faster than dry soil does — stand it somewhere humid.",
			Desc:    "Wiry black stalks carrying fan-shaped leaflets so water-repellent that a frond dipped in a stream comes out dry. It grows wild on dripping limestone and around springs.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 7, Unlock: 6, Hours: 17,
			Palette: Palette{Stem: "238", Leaf: "114", Bloom: "150", Accent: "108"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ¸  "},
				{" ~│~ "},
				{" ~~~ ", " ╲│╱ "},
				{" ~~~~ ", "~~~~~~", " ╲╲│╱╱", "   │  "},
			},
		},
		&Species{
			ID: "ostrichfern", Common: "Ostrich Fern", Latin: "Matteuccia struthiopteris",
			Family: "Onocleaceae", Kind: KindFern, Rarity: Uncommon,
			Origin: "cool temperate northern hemisphere", Bloom: "none; spores on separate brown fronds",
			Sun: "shade to part shade", Water: "moist, even boggy", Height: "1–1.7 m",
			Note:    "Never strip a crown bare — take at most half the fiddleheads in spring.",
			Desc:    "A shuttlecock of arching fronds, whose tightly coiled young fiddleheads are eaten as a spring vegetable in Japan and eastern Canada. They must be cooked thoroughly; raw ones make people ill.",
			Seasons: []Season{Spring, Summer}, SeedCost: 7, Unlock: 7, Hours: 18,
			Palette: Palette{Stem: "65", Leaf: "71", Bloom: "101", Accent: "108"},
			Glyphs:  map[rune]glyphClass{'ϟ': clLeaf},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϟ  "},
				{" ϟ│ϟ "},
				{" ζ│ζ ", " ╲│╱ "},
				{"ζ ζ ζ ", " ζ│ζ  ", " ╲│╱  ", "  │   "},
			},
		},
		&Species{
			ID: "haircapmoss", Common: "Common Haircap Moss", Latin: "Polytrichum commune",
			Family: "Polytrichaceae", Kind: KindFern, Rarity: Common,
			Origin: "bogs and damp woods worldwide", Bloom: "spore capsules on fine red stalks",
			Sun: "shade", Water: "keep it damp", Height: "5–20 cm",
			Note:    "It has no roots — press it onto the surface and mist rather than burying it.",
			Desc:    "One of the tallest mosses, with a primitive internal plumbing of water-conducting cells that lets it stand upright where other mosses lie flat. Whole cushions can dry to a crisp and green up again within minutes of rain.",
			Seasons: []Season{Spring, Summer, Autumn, Winter}, SeedCost: 3, Unlock: 1, Hours: 13,
			Palette: Palette{Stem: "101", Leaf: "65", Bloom: "137", Accent: "144"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ,  "},
				{" ,,, "},
				{" ¦¦¦ ", " ,,, "},
				{"¦ ¦ ¦", "¦¦¦¦¦", ",,,,,"},
			},
		},
		&Species{
			ID: "hosta", Common: "Siebold's Hosta", Latin: "Hosta sieboldiana",
			Family: "Asparagaceae", Kind: KindFern, Rarity: Common,
			Origin: "Japan", Bloom: "pale lilac spires in midsummer",
			Sun: "shade", Water: "moist", Height: "50–80 cm",
			Note:    "Slugs treat it as a salad bar; a ring of grit or copper helps.",
			Desc:    "Grown for its leaves rather than its flowers: heavily ribbed, blue-grey and puckered, the blue coming from a waxy coating that sun and hard rain gradually wash away.",
			Seasons: []Season{Spring, Summer}, SeedCost: 5, Unlock: 3, Hours: 17,
			Palette: Palette{Stem: "72", Leaf: "109", Bloom: "182", Accent: "146"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з "},
				{" εзε ", " ╲│╱ "},
				{"  ❋  ", " ε│з ", "εз│зε", " ╲│╱ "},
			},
		},
		&Species{
			ID: "bamboo", Common: "Golden Bamboo", Latin: "Phyllostachys aurea",
			Family: "Poaceae", Kind: KindGrass, Rarity: Uncommon,
			Origin: "southeastern China", Bloom: "once in decades, then the grove dies",
			Sun: "sun to part shade", Water: "moderate", Height: "6–10 m",
			Note:    "Sink a root barrier before planting, or plant it in a pot. Really.",
			Desc:    "A running bamboo that can add tens of centimetres a day at full tilt, each new culm emerging at its final thickness. Whole groves flower simultaneously on a decades-long internal clock and then die back together.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 8, Unlock: 8, Hours: 17,
			Palette: Palette{Stem: "185", Leaf: "107", Bloom: "228", Accent: "143"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ¦  "},
				{" ¦│¦ "},
				{" ζ│ζ ", " ¦│¦ "},
				{"ζ│ │ζ", " │ │ ", " ├─┤ ", " │ │ "},
			},
		},
		&Species{
			ID: "fountaingrass", Common: "Fountain Grass", Latin: "Cenchrus alopecuroides",
			Family: "Poaceae", Kind: KindGrass, Rarity: Common,
			Origin: "eastern Asia and Australia", Bloom: "bottlebrush plumes in late summer",
			Sun: "full sun", Water: "low once established", Height: "60–120 cm",
			Note:    "Cut the whole clump to the ground in late winter, before new growth starts.",
			Desc:    "A clump-forming grass whose arching flower spikes catch low autumn light and hold their shape well into winter. Long known as Pennisetum, it was reclassified into Cenchrus.",
			Seasons: []Season{Summer, Autumn}, SeedCost: 4, Unlock: 2, Hours: 16,
			Palette: Palette{Stem: "108", Leaf: "107", Bloom: "180", Accent: "223"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ¦  "},
				{" ╲│╱ "},
				{" ╲│╱ ", " ╲│╱ "},
				{"~ ~ ~ ", " ╲│╱  ", "╲╲│╱╱ ", "  │   "},
			},
		},
		&Species{
			ID: "venusflytrap", Common: "Venus Flytrap", Latin: "Dionaea muscipula",
			Family: "Droseraceae", Kind: KindCarnivore, Rarity: Legendary,
			Origin: "a 100 km radius of Wilmington, North Carolina", Bloom: "white flowers on a tall stalk",
			Sun: "full sun", Water: "rain or distilled water only — never tap", Height: "10–15 cm",
			Note:    "Do not tease the traps. Each one can close only a handful of times.",
			Desc:    "A trap snaps shut when two trigger hairs are touched within about twenty seconds, a crude timer that ignores raindrops. It grows wild in nutrient-poor bogs in one small corner of the Carolinas and nowhere else on Earth.",
			Seasons: []Season{Spring, Summer}, SeedCost: 16, Unlock: 24, Hours: 19,
			Palette: Palette{Stem: "71", Leaf: "77", Bloom: "255", Accent: "161"},
			Glyphs:  map[rune]glyphClass{'◆': clAccent},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ϑ│ϑ "},
				{" ◆│◆ ", " ╲│╱ "},
				{" ◆ ◆ ", " ╲│╱ ", " ◆│◆ ", "  │  "},
			},
		},
		&Species{
			ID: "pitcherplant", Common: "Purple Pitcher Plant", Latin: "Sarracenia purpurea",
			Family: "Sarraceniaceae", Kind: KindCarnivore, Rarity: Rare,
			Origin: "bogs of eastern North America", Bloom: "a nodding maroon flower in spring",
			Sun: "full sun", Water: "standing in rainwater", Height: "20–40 cm",
			Note:    "Never feed it fertiliser; bog plants read rich soil as poison.",
			Desc:    "Rainwater collects in the squat pitchers, and downward-pointing hairs make climbing out impossible for insects that slip in. A whole community of mosquito larvae and midges lives in that fluid without being digested.",
			Seasons: []Season{Spring, Summer}, SeedCost: 12, Unlock: 16, Hours: 19,
			Palette: Palette{Stem: "71", Leaf: "65", Bloom: "125", Accent: "161"},
			Glyphs:  map[rune]glyphClass{'▮': clAccent},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ¸  "},
				{" ▮ ▮ "},
				{" ▮ ▮ ", " ╲│╱ "},
				{" ❀▮ ▮ ", " ▮│▮  ", " ╲│╱  ", "  │   "},
			},
		},
		&Species{
			ID: "sundew", Common: "Round-leaved Sundew", Latin: "Drosera rotundifolia",
			Family: "Droseraceae", Kind: KindCarnivore, Rarity: Rare,
			Origin: "bogs across the northern hemisphere", Bloom: "small white flowers in summer",
			Sun: "full sun", Water: "permanently wet, rainwater only", Height: "5–10 cm",
			Note:    "Those droplets are glue, not dew, and they do not evaporate in the sun.",
			Desc:    "Each leaf is fringed with tentacles tipped in sticky mucilage. When prey sticks, the tentacles bend inward over minutes to hours, folding the insect into the leaf where digestion begins.",
			Seasons: []Season{Spring, Summer}, SeedCost: 12, Unlock: 18, Hours: 18,
			Palette: Palette{Stem: "71", Leaf: "167", Bloom: "255", Accent: "224"},
			Glyphs:  map[rune]glyphClass{'˙': clAccent},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ,  "},
				{" ˙,˙ "},
				{" ˙~˙ ", " ~,~ "},
				{" ˙~˙~˙", " ~˙~˙~", " ╲╲│╱╱"},
			},
		},
		&Species{
			ID: "mothorchid", Common: "Moth Orchid", Latin: "Phalaenopsis amabilis",
			Family: "Orchidaceae", Kind: KindFlower, Rarity: Rare,
			Origin: "Southeast Asia, New Guinea and Queensland", Bloom: "for months, once a year",
			Sun: "bright, indirect light", Water: "weekly soak, then drain fully", Height: "40–70 cm",
			Note:    "It grows on bark, not soil: the thick grey roots want air as much as water.",
			Desc:    "An epiphyte that perches on trees rather than rooting in the ground, its silvery aerial roots photosynthesising alongside the leaves. Left in place after flowering, an old spike will often branch and bloom again.",
			Seasons: []Season{Spring, Summer, Autumn, Winter}, SeedCost: 14, Unlock: 20, Hours: 20,
			Palette: Palette{Stem: "108", Leaf: "71", Bloom: "255", Accent: "218"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з "},
				{" ◦│  ", " ε│з ", " ╲│╱ "},
				{" ❀╮  ", " ❀│  ", " ❀│  ", "ε╲│╱з"},
			},
		},
		&Species{
			ID: "waterlily", Common: "Fragrant Water Lily", Latin: "Nymphaea odorata",
			Family: "Nymphaeaceae", Kind: KindAquatic, Rarity: Rare,
			Origin: "ponds and slow rivers of North America", Bloom: "summer mornings",
			Sun: "full sun", Water: "a pond, 30–60 cm deep", Height: "floating",
			Note:    "The flowers open in the morning and close by afternoon for three days, then sink.",
			Desc:    "Leaves float on long flexible stalks anchored in the mud, with pores on the upper surface rather than the lower — the only sensible arrangement when your underside is underwater.",
			Seasons: []Season{Summer}, SeedCost: 13, Unlock: 18, Hours: 19,
			Palette: Palette{Stem: "72", Leaf: "71", Bloom: "255", Accent: "218"},
			Glyphs:  map[rune]glyphClass{'◠': clLeaf, '≈': clStem},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ≈  "},
				{" ≈◠≈ "},
				{" ◠ ◠ ", " ≈≈≈ "},
				{" ◠ ❀ ◠", "≈≈≈≈≈≈", " ≈≈≈≈ "},
			},
		},
		&Species{
			ID: "lotus", Common: "Sacred Lotus", Latin: "Nelumbo nucifera",
			Family: "Nelumbonaceae", Kind: KindAquatic, Rarity: Legendary,
			Origin: "Asia and northern Australia", Bloom: "midsummer, for three days each",
			Sun: "full sun", Water: "warm, still water over deep mud", Height: "1–1.5 m above the water",
			Note:    "It needs real summer heat to flower; a cold pond gives leaves and nothing else.",
			Desc:    "Leaves are so finely textured that water rolls off carrying the dirt with it, the effect engineers now copy as the lotus effect. The flowers warm themselves above air temperature to attract beetles, and seeds over a thousand years old have been germinated successfully.",
			Seasons: []Season{Summer}, SeedCost: 22, Unlock: 35, Hours: 20,
			Palette: Palette{Stem: "72", Leaf: "108", Bloom: "218", Accent: "228"},
			Glyphs:  map[rune]glyphClass{'◠': clLeaf, '≈': clStem},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ≈  "},
				{" ≈◠≈ "},
				{" ◠│◠ ", " ≈│≈ ", "  │  "},
				{" ❀ ◠ ", " ╲│╱ ", "◠ │ ◠", "≈≈│≈≈"},
			},
		},
	)
}
