package main

// The herb bed: kitchen plants, most of them Mediterranean and most of them
// happiest when slightly neglected.
func init() {
	register(
		&Species{
			ID: "basil", Common: "Sweet Basil", Latin: "Ocimum basilicum",
			Family: "Lamiaceae", Kind: KindHerb, Rarity: Common,
			Origin: "tropical Asia and Africa", Bloom: "midsummer, pinch it off",
			Sun: "full sun, warmth", Water: "even moisture, never cold", Height: "30–60 cm",
			Note:    "Pinch out the growing tip above a leaf pair and one plant becomes a bush.",
			Desc:    "A tender annual of the mint family, holy in India as tulsi's close relative and indispensable in Italian and Thai kitchens. It sulks below about 10°C, so it goes out only when nights are reliably warm.",
			Seasons: []Season{Summer}, SeedCost: 2, Unlock: 0, Hours: 12,
			Palette: Palette{Stem: "65", Leaf: "77", Bloom: "255", Accent: "194"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" ε│з ", " ε│з ", "  │  "},
				{" ε❁з ", " ε│з ", " ε│з ", "  │  "},
			},
		},
		&Species{
			ID: "rosemary", Common: "Rosemary", Latin: "Salvia rosmarinus",
			Family: "Lamiaceae", Kind: KindHerb, Rarity: Common,
			Origin: "Mediterranean coast", Bloom: "late winter into spring",
			Sun: "full sun", Water: "low; sharp drainage", Height: "1–1.5 m",
			Note:    "Kill it with kindness and it rots — water less than feels right.",
			Desc:    "A woody evergreen shrub whose name means 'dew of the sea'. Recent DNA work moved it out of its own genus and into Salvia. Pale blue flowers appear early enough to feed the year's first bees.",
			Seasons: []Season{Spring, Summer, Autumn, Winter}, SeedCost: 4, Unlock: 1, Hours: 17,
			Palette: Palette{Stem: "58", Leaf: "65", Bloom: "111", Accent: "153"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ¦  "},
				{" ¦│¦ ", "  │  "},
				{" ¦│¦ ", " ¦│¦ ", "  │  "},
				{" ¦❋¦ ", " ❋│¦ ", " ¦│❋ ", " ¦│¦ ", "  │  "},
			},
		},
		&Species{
			ID: "thyme", Common: "Common Thyme", Latin: "Thymus vulgaris",
			Family: "Lamiaceae", Kind: KindHerb, Rarity: Common,
			Origin: "western Mediterranean", Bloom: "early summer",
			Sun: "full sun", Water: "low", Height: "15–30 cm",
			Note:    "Clip it after flowering to stop the middle going woody and bare.",
			Desc:    "A low, wiry sub-shrub carrying an enormous amount of flavour in very small leaves. Thymol, its main oil, is a genuine antiseptic, which is why the Romans burned thyme to purify rooms.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 3, Unlock: 0, Hours: 13,
			Palette: Palette{Stem: "58", Leaf: "71", Bloom: "176", Accent: "182"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ,  "},
				{" ~~~ "},
				{" ~~~ ", " ╲│╱ "},
				{" ❁~❁ ", " ~❁~ ", " ╲│╱ "},
			},
		},
		&Species{
			ID: "mint", Common: "Peppermint", Latin: "Mentha × piperita",
			Family: "Lamiaceae", Kind: KindHerb, Rarity: Common,
			Origin: "a European hybrid of water mint and spearmint", Bloom: "midsummer",
			Sun: "sun or part shade", Water: "keep it damp", Height: "30–90 cm",
			Note:    "Grow it in a sunken pot unless you want mint everywhere forever.",
			Desc:    "A sterile hybrid that spreads entirely by runner, which is exactly why it takes over beds. Menthol in the leaves triggers the same cold receptors in the mouth as low temperature does.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 2, Unlock: 0, Hours: 12,
			Palette: Palette{Stem: "65", Leaf: "78", Bloom: "176", Accent: "182"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" ε│з ", " ε│з ", "  │  "},
				{" ε❋з ", " ε│з ", " ε│з ", " ε│з "},
			},
		},
		&Species{
			ID: "sage", Common: "Common Sage", Latin: "Salvia officinalis",
			Family: "Lamiaceae", Kind: KindHerb, Rarity: Common,
			Origin: "northern Mediterranean", Bloom: "early summer",
			Sun: "full sun", Water: "low", Height: "60–80 cm",
			Note:    "Replace the plant every four or five years, once the base turns to bare wood.",
			Desc:    "Grey, pebbled evergreen leaves on a woody frame, with flowers whose stamens work like a lever: a bee pushing in tips pollen neatly onto its back. Officinalis in the name means it was a plant of the apothecary's store.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 3, Unlock: 1, Hours: 15,
			Palette: Palette{Stem: "65", Leaf: "108", Bloom: "104", Accent: "146"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" ε│з ", " ε│з ", "  │  "},
				{" ❋│❋ ", " ε│з ", " ε│з ", "  │  "},
			},
		},
		&Species{
			ID: "lavender", Common: "English Lavender", Latin: "Lavandula angustifolia",
			Family: "Lamiaceae", Kind: KindHerb, Rarity: Uncommon,
			Origin: "western Mediterranean", Bloom: "midsummer",
			Sun: "full sun", Water: "low; hates wet feet", Height: "40–80 cm",
			Note:    "Trim to a neat dome after flowering, but never cut back into old wood.",
			Desc:    "Silvery evergreen foliage under spikes of scented flowers that draw bees from a distance. Grown commercially for oil since the Middle Ages; the name comes from the Latin lavare, to wash.",
			Seasons: []Season{Spring, Summer}, SeedCost: 5, Unlock: 3, Hours: 17,
			Palette: Palette{Stem: "108", Leaf: "108", Bloom: "141", Accent: "183"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ¦  "},
				{" ¦│¦ ", "  │  "},
				{" ◦¦◦ ", " ¦│¦ ", "  │  "},
				{" ❋ ❋ ", " ¦ ¦ ", " ╲│╱ ", " ¦│¦ ", "  │  "},
			},
		},
		&Species{
			ID: "chamomile", Common: "German Chamomile", Latin: "Matricaria chamomilla",
			Family: "Asteraceae", Kind: KindHerb, Rarity: Common,
			Origin: "Europe and western Asia", Bloom: "all summer",
			Sun: "full sun", Water: "low", Height: "20–50 cm",
			Note:    "Pick the flowers in the morning once the petals have bent back.",
			Desc:    "A feathery annual whose small daisies smell of apples — the Greek name means 'earth apple'. Dried heads make the familiar tea, and the plant self-sows politely wherever it is happy.",
			Seasons: []Season{Spring, Summer}, SeedCost: 3, Unlock: 0, Hours: 13,
			Palette: Palette{Stem: "71", Leaf: "78", Bloom: "255", Accent: "220"},
			Glyphs:  map[rune]glyphClass{'○': clAccent},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ~  "},
				{" ~│~ ", "  │  "},
				{" ◦ ◦ ", " ~│~ ", "  │  "},
				{" ✿ ✿ ", " ╲│╱ ", " ~│~ ", "  │  "},
			},
		},
		&Species{
			ID: "chives", Common: "Chives", Latin: "Allium schoenoprasum",
			Family: "Amaryllidaceae", Kind: KindHerb, Rarity: Common,
			Origin: "Europe, Asia and North America", Bloom: "late spring",
			Sun: "full sun", Water: "moderate", Height: "20–40 cm",
			Note:    "Shear the whole clump to 5 cm and it regrows tender within a fortnight.",
			Desc:    "The smallest cultivated onion, and the only Allium native to both the Old and New Worlds. The mauve pompom flowers are edible too, and the clump divides easily every few years.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 2, Unlock: 0, Hours: 12,
			Palette: Palette{Stem: "72", Leaf: "78", Bloom: "176", Accent: "182"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ¦  "},
				{" ¦¦¦ "},
				{" ¦¦¦ ", " ¦¦¦ "},
				{" ❋ ❋ ", " ¦¦¦ ", " ¦¦¦ ", " ╲│╱ "},
			},
		},
		&Species{
			ID: "parsley", Common: "Curly Parsley", Latin: "Petroselinum crispum",
			Family: "Apiaceae", Kind: KindHerb, Rarity: Common,
			Origin: "central Mediterranean", Bloom: "in its second year",
			Sun: "sun to light shade", Water: "even moisture", Height: "25–40 cm",
			Note:    "Slow to germinate — soak the seed and expect three weeks of nothing.",
			Desc:    "A biennial grown as an annual for its leaves, rich in vitamin C and iron. Left to its second year it throws a flat umbel of tiny flowers that hoverflies and parasitic wasps work over eagerly.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 2, Unlock: 0, Hours: 13,
			Palette: Palette{Stem: "71", Leaf: "77", Bloom: "228", Accent: "194"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" εзε ", "  │  "},
				{" εзε ", " εзε ", "  │  "},
				{" εзεз ", " εзεз ", " ε╲│╱з", "   │  "},
			},
		},
		&Species{
			ID: "dill", Common: "Dill", Latin: "Anethum graveolens",
			Family: "Apiaceae", Kind: KindHerb, Rarity: Common,
			Origin: "the eastern Mediterranean and western Asia", Bloom: "midsummer",
			Sun: "full sun", Water: "moderate", Height: "60–120 cm",
			Note:    "Sow it in succession every three weeks — it bolts the moment it is happy.",
			Desc:    "Feathery blue-green foliage under a wide yellow umbel, used whole for pickling. It is a host plant for swallowtail caterpillars, so a chewed plant is usually good news.",
			Seasons: []Season{Spring, Summer}, SeedCost: 3, Unlock: 1, Hours: 13,
			Palette: Palette{Stem: "72", Leaf: "79", Bloom: "227", Accent: "185"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ~  "},
				{" ~│~ ", "  │  "},
				{" ~~~ ", " ~│~ ", "  │  "},
				{" ✻✻✻ ", " ╲│╱ ", " ~│~ ", "  │  "},
			},
		},
		&Species{
			ID: "oregano", Common: "Greek Oregano", Latin: "Origanum vulgare",
			Family: "Lamiaceae", Kind: KindHerb, Rarity: Common,
			Origin: "Mediterranean and western Asia", Bloom: "mid to late summer",
			Sun: "full sun", Water: "low", Height: "30–60 cm",
			Note:    "The flavour is strongest just before the flowers open.",
			Desc:    "A spreading perennial whose name means 'joy of the mountain'. Hot, dry conditions concentrate the oils; the same plant grown in rich damp soil tastes of almost nothing.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 3, Unlock: 0, Hours: 13,
			Palette: Palette{Stem: "65", Leaf: "71", Bloom: "182", Accent: "218"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з "},
				{" ε│з ", " ε│з "},
				{" ❁❁❁ ", " ε│з ", " ε│з ", " ╲│╱ "},
			},
		},
		&Species{
			ID: "lemonbalm", Common: "Lemon Balm", Latin: "Melissa officinalis",
			Family: "Lamiaceae", Kind: KindHerb, Rarity: Common,
			Origin: "southern Europe and central Asia", Bloom: "summer",
			Sun: "sun or part shade", Water: "moderate", Height: "40–80 cm",
			Note:    "Cut it back hard in midsummer for a fresh flush of scented leaves.",
			Desc:    "Crushed leaves smell sharply of lemon. Melissa is Greek for honeybee: beekeepers once rubbed the leaves inside empty hives to encourage a swarm to move in and stay.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 3, Unlock: 1, Hours: 13,
			Palette: Palette{Stem: "71", Leaf: "113", Bloom: "255", Accent: "228"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" ε│з ", " ε│з ", "  │  "},
				{" ε❁з ", " ε│з ", " ε│з ", " ╲│╱ "},
			},
		},
	)
}
