package main

// Succulents and cacti: the plants that forgive a gardener who forgets.
func init() {
	register(
		&Species{
			ID: "aloe", Common: "Aloe Vera", Latin: "Aloe vera",
			Family: "Asphodelaceae", Kind: KindSucculent, Rarity: Common,
			Origin: "the Arabian peninsula", Bloom: "yellow spikes on mature plants",
			Sun: "bright light", Water: "soak, then let it dry out completely", Height: "60–100 cm",
			Note:    "Take offsets from the base once they have three or four leaves of their own.",
			Desc:    "Known in cultivation so long that no certain wild population remains. The thick leaves hold a clear gel long used on burns, sitting just inside a bitter yellow latex layer that most people find unpleasant.",
			Seasons: []Season{Spring, Summer, Autumn, Winter}, SeedCost: 4, Unlock: 2, Hours: 17,
			Palette: Palette{Stem: "72", Leaf: "108", Bloom: "214", Accent: "150"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ¦  "},
				{" ╲│╱ "},
				{" ╲│╱ ", " ╲│╱ "},
				{"  ❋  ", "╲ │ ╱", "╲╲│╱╱"},
			},
		},
		&Species{
			ID: "jade", Common: "Jade Plant", Latin: "Crassula ovata",
			Family: "Crassulaceae", Kind: KindSucculent, Rarity: Common,
			Origin: "South Africa and Mozambique", Bloom: "small white stars in winter",
			Sun: "bright light", Water: "sparingly, less in winter", Height: "1–2 m over decades",
			Note:    "A single fallen leaf laid on dry compost will root into a new plant.",
			Desc:    "A slow, thick-trunked succulent that can outlive its owner, kept as a luck plant in many households. Like most crassulas it breathes at night, opening its pores after dark to save water in the heat.",
			Seasons: []Season{Spring, Summer, Autumn, Winter}, SeedCost: 5, Unlock: 3, Hours: 18,
			Palette: Palette{Stem: "95", Leaf: "71", Bloom: "255", Accent: "218"},
			Glyphs:  map[rune]glyphClass{'●': clLeaf},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ●  "},
				{" ●│● ", "  │  "},
				{" ●│● ", " ●│● ", "  │  "},
				{" ●●●● ", "●●│●● ", " ●│●  ", "  │   "},
			},
		},
		&Species{
			ID: "sempervivum", Common: "Hens and Chicks", Latin: "Sempervivum tectorum",
			Family: "Crassulaceae", Kind: KindSucculent, Rarity: Common,
			Origin: "the mountains of southern Europe", Bloom: "once, then that rosette dies",
			Sun: "full sun", Water: "very little", Height: "8–15 cm",
			Note:    "It wants grit, not compost — plant it in something that drains instantly.",
			Desc:    "Tight rosettes that ring themselves with offsets, the 'chicks' of the name. Sempervivum means 'always alive': it was grown on roofs across Europe in the belief that it kept lightning away.",
			Seasons: []Season{Spring, Summer, Autumn, Winter}, SeedCost: 4, Unlock: 2, Hours: 16,
			Palette: Palette{Stem: "72", Leaf: "108", Bloom: "175", Accent: "131"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ▲  "},
				{" ╲▲╱ "},
				{" ╲▲╱ ", " ╲ ╱ "},
				{" ╲▲╱ ", "▲╲▲╱▲", "╲╱ ╲╱"},
			},
		},
		&Species{
			ID: "barrelcactus", Common: "Golden Barrel Cactus", Latin: "Echinocactus grusonii",
			Family: "Cactaceae", Kind: KindSucculent, Rarity: Rare,
			Origin: "a small area of eastern Mexico", Bloom: "yellow crown after twenty years or so",
			Sun: "full sun", Water: "almost none in winter", Height: "60–100 cm",
			Note:    "Wear gloves. The spines are as unforgiving as they look.",
			Desc:    "A ribbed golden barrel, common in cultivation and endangered in the wild, where a dam flooded much of its habitat. The ribs work like an accordion, swelling after rain and contracting through drought.",
			Seasons: []Season{Spring, Summer, Autumn, Winter}, SeedCost: 10, Unlock: 12, Hours: 20,
			Palette: Palette{Stem: "65", Leaf: "71", Bloom: "226", Accent: "228"},
			Glyphs:  map[rune]glyphClass{'▮': clLeaf, '¦': clAccent},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ▮  "},
				{" ¦▮¦ "},
				{" ¦▮▮¦ ", " ¦▮▮¦ "},
				{" ❋❋❋ ", "¦▮▮▮¦", "¦▮▮▮¦", " ▮▮▮ "},
			},
		},
		&Species{
			ID: "pricklypear", Common: "Prickly Pear", Latin: "Opuntia ficus-indica",
			Family: "Cactaceae", Kind: KindSucculent, Rarity: Uncommon,
			Origin: "Mexico", Bloom: "yellow to orange in early summer",
			Sun: "full sun", Water: "rarely", Height: "3–5 m",
			Note:    "The hair-fine glochids hurt more than the spines; handle pads with tongs.",
			Desc:    "Grown across the dry world for its fruit and its pads, both eaten as food. It also hosts the cochineal insect, the source of carmine dye, which once made it a crop of serious commercial value.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 7, Unlock: 6, Hours: 19,
			Palette: Palette{Stem: "65", Leaf: "72", Bloom: "214", Accent: "197"},
			Glyphs:  map[rune]glyphClass{'▮': clLeaf},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ▮  "},
				{"  ▮  ", "  ▮  "},
				{" ▮▮  ", "  ▮  ", "  ▮  "},
				{" ❀▮ ▮ ", " ▮▮▮  ", "  ▮   ", "  ▮   "},
			},
		},
		&Species{
			ID: "stringofpearls", Common: "String of Pearls", Latin: "Curio rowleyanus",
			Family: "Asteraceae", Kind: KindSucculent, Rarity: Rare,
			Origin: "the dry interior of South Africa", Bloom: "small white brushes that smell of cinnamon",
			Sun: "bright, indirect light", Water: "sparse; it rots in a heartbeat", Height: "trails 60–90 cm",
			Note:    "Lay a strand across the compost surface and it roots at every node.",
			Desc:    "Each bead is a leaf rolled almost into a sphere to cut water loss, with a translucent window along one side letting light reach the chlorophyll inside. Recently moved out of Senecio into the genus Curio.",
			Seasons: []Season{Spring, Summer, Autumn, Winter}, SeedCost: 11, Unlock: 13, Hours: 19,
			Palette: Palette{Stem: "108", Leaf: "114", Bloom: "255", Accent: "150"},
			Glyphs:  map[rune]glyphClass{'○': clLeaf},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ○  "},
				{"  ○  ", "  ○  "},
				{" ○ ○ ", " ○ ○ ", "  ○  "},
				{" ○ ○ ○", " ○ ○ ○", " ○ ○ ○", "  ○ ○ "},
			},
		},
		&Species{
			ID: "echeveria", Common: "Mexican Snowball", Latin: "Echeveria elegans",
			Family: "Crassulaceae", Kind: KindSucculent, Rarity: Uncommon,
			Origin: "semi-desert Mexico", Bloom: "pink bells on an arching stalk",
			Sun: "full sun to bright light", Water: "let it dry right out between drinks", Height: "10–20 cm",
			Note:    "Water the soil, never the rosette: trapped water in the centre rots it.",
			Desc:    "A pale blue-green rosette dusted with farina, a natural waxy bloom that works as sunscreen and water-repellent coat at once. Rub it off with your fingers and it does not grow back on that leaf.",
			Seasons: []Season{Spring, Summer, Autumn, Winter}, SeedCost: 6, Unlock: 4, Hours: 17,
			Palette: Palette{Stem: "108", Leaf: "151", Bloom: "211", Accent: "218"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ▲  "},
				{" ╲▲╱ "},
				{" ╲▲╱ ", " ╲ ╱ "},
				{"  ❁  ", " ╲▲╱ ", "╲╲▲╱╱"},
			},
		},
	)
}
