package main

// Bulbs and the plants that climb: the spring parade and the summer climbers.
func init() {
	register(
		&Species{
			ID: "tulip", Common: "Garden Tulip", Latin: "Tulipa gesneriana",
			Family: "Liliaceae", Kind: KindBulb, Rarity: Common,
			Origin: "Central Asia, via Ottoman gardens", Bloom: "mid to late spring",
			Sun: "full sun", Water: "moderate in growth, dry in summer", Height: "30–60 cm",
			Note:    "Plant the bulbs three times their own depth, pointed end up, in autumn.",
			Desc:    "The tulip reached Europe from Ottoman Turkey in the sixteenth century and set off the speculative frenzy remembered as tulip mania. Flowers close at night and in rain, opening wide again in sun.",
			Seasons: []Season{Spring}, SeedCost: 4, Unlock: 1, Hours: 16,
			Palette: Palette{Stem: "71", Leaf: "77", Bloom: "197", Accent: "220"},
			Art: [StageCount][]string{
				{"  ●  "},
				{"  ϑ  "},
				{" ζ│ζ ", "  │  "},
				{"  ◍  ", "  │  ", " ζ│ζ "},
				{" ╲❀╱ ", "  │  ", " ζ│ζ ", "  │  "},
			},
		},
		&Species{
			ID: "daffodil", Common: "Wild Daffodil", Latin: "Narcissus pseudonarcissus",
			Family: "Amaryllidaceae", Kind: KindBulb, Rarity: Common,
			Origin: "western Europe", Bloom: "early spring",
			Sun: "sun to light shade", Water: "moderate", Height: "20–35 cm",
			Note:    "Let the leaves yellow naturally; they are feeding next year's flower.",
			Desc:    "The Lent lily of old English woods, with a pale ruff of petals around a deeper trumpet. Bulbs contain lycorine, which is why deer, squirrels and mice leave them strictly alone.",
			Seasons: []Season{Winter, Spring}, SeedCost: 4, Unlock: 1, Hours: 15,
			Palette: Palette{Stem: "71", Leaf: "77", Bloom: "227", Accent: "214"},
			Glyphs:  map[rune]glyphClass{'○': clAccent},
			Art: [StageCount][]string{
				{"  ●  "},
				{"  ϑ  "},
				{" ζ│ζ ", "  │  "},
				{"  ◦  ", "  │  ", " ζ│ζ "},
				{" ✿○✿ ", "  │  ", " ζ│ζ ", "  │  "},
			},
		},
		&Species{
			ID: "crocus", Common: "Spring Crocus", Latin: "Crocus vernus",
			Family: "Iridaceae", Kind: KindBulb, Rarity: Common,
			Origin: "the Alps and Balkans", Bloom: "late winter to early spring",
			Sun: "full sun", Water: "low", Height: "8–15 cm",
			Note:    "Naturalise them in grass and mow only after the leaves die down.",
			Desc:    "A corm, not a true bulb, pushing goblet flowers through late snow. They open on warm afternoons to give early bees their first pollen of the year and shut tight again by evening.",
			Seasons: []Season{Winter, Spring}, SeedCost: 3, Unlock: 0, Hours: 13,
			Palette: Palette{Stem: "72", Leaf: "78", Bloom: "141", Accent: "220"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ¦  "},
				{" ¦│¦ "},
				{" ¦◦¦ ", " ¦│¦ "},
				{" ╲✿╱ ", " ¦│¦ ", "  │  "},
			},
		},
		&Species{
			ID: "snowdrop", Common: "Snowdrop", Latin: "Galanthus nivalis",
			Family: "Amaryllidaceae", Kind: KindBulb, Rarity: Uncommon,
			Origin: "Europe, from the Pyrenees to Ukraine", Bloom: "late winter",
			Sun: "shade to part sun", Water: "moist in winter and spring", Height: "10–15 cm",
			Note:    "Move them 'in the green', just after flowering, rather than as dry bulbs.",
			Desc:    "The first flower of the year in much of Europe, whose leaf tips are hardened to push through frozen ground. Galantamine, extracted from the bulbs, is used in the treatment of Alzheimer's disease.",
			Seasons: []Season{Winter}, SeedCost: 6, Unlock: 4, Hours: 13,
			Palette: Palette{Stem: "72", Leaf: "78", Bloom: "255", Accent: "194"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ¦  "},
				{" ¦│¦ "},
				{" ¦◦¦ ", " ¦│¦ "},
				{"  ╭╮ ", " ¦❀¦ ", " ¦│¦ "},
			},
		},
		&Species{
			ID: "iris", Common: "Bearded Iris", Latin: "Iris germanica",
			Family: "Iridaceae", Kind: KindBulb, Rarity: Uncommon,
			Origin: "southern Europe", Bloom: "late spring",
			Sun: "full sun", Water: "low; rhizomes must bake", Height: "60–90 cm",
			Note:    "Leave the rhizome half exposed on the soil surface — buried, it rots.",
			Desc:    "Named for the Greek goddess of the rainbow, with three upright standards, three falling petals and a fuzzy 'beard' that guides bees into the flower. The fleur-de-lis of French heraldry is a stylised iris.",
			Seasons: []Season{Spring, Summer}, SeedCost: 6, Unlock: 4, Hours: 17,
			Palette: Palette{Stem: "71", Leaf: "78", Bloom: "99", Accent: "227"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ¦  "},
				{" ¦│¦ ", "  │  "},
				{" ¦◦¦ ", " ¦│¦ ", "  │  "},
				{" ╲❋╱ ", " ¦│¦ ", " ¦│¦ ", "  │  "},
			},
		},
		&Species{
			ID: "lilyvalley", Common: "Lily of the Valley", Latin: "Convallaria majalis",
			Family: "Asparagaceae", Kind: KindBulb, Rarity: Rare,
			Origin: "temperate Europe and Asia", Bloom: "late spring",
			Sun: "shade", Water: "evenly moist", Height: "15–25 cm",
			Note:    "Give it a corner it can colonise; it spreads by creeping rhizome.",
			Desc:    "A shade-loving spreader hung with waxy white bells whose scent carries far further than the plant's size suggests. Every part, including the red autumn berries, is poisonous.",
			Seasons: []Season{Spring}, SeedCost: 9, Unlock: 9, Hours: 17,
			Palette: Palette{Stem: "71", Leaf: "77", Bloom: "255", Accent: "196"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з "},
				{" ε│з ", " ◦│  "},
				{" ε│❀ ", " ε│❀ ", " ε│❀ ", "  │  "},
			},
		},
		&Species{
			ID: "hyacinth", Common: "Hyacinth", Latin: "Hyacinthus orientalis",
			Family: "Asparagaceae", Kind: KindBulb, Rarity: Uncommon,
			Origin: "eastern Mediterranean", Bloom: "mid spring",
			Sun: "full sun", Water: "moderate", Height: "20–30 cm",
			Note:    "One bulb in a glass of water on a windowsill will flower all by itself.",
			Desc:    "A dense, waxy spike of star flowers with a scent strong enough to fill a room. Dutch growers have bred it since the seventeenth century; in the 1730s single bulbs changed hands for the price of a house.",
			Seasons: []Season{Spring}, SeedCost: 6, Unlock: 5, Hours: 15,
			Palette: Palette{Stem: "72", Leaf: "78", Bloom: "104", Accent: "141"},
			Art: [StageCount][]string{
				{"  ●  "},
				{"  ¦  "},
				{" ¦│¦ "},
				{" ¦◍¦ ", " ¦│¦ "},
				{" ❋❋❋ ", " ❋❋❋ ", " ¦│¦ ", "  │  "},
			},
		},
		&Species{
			ID: "allium", Common: "Giant Allium", Latin: "Allium giganteum",
			Family: "Amaryllidaceae", Kind: KindBulb, Rarity: Rare,
			Origin: "central Asia", Bloom: "early summer",
			Sun: "full sun", Water: "low", Height: "1–1.5 m",
			Note:    "Leave the dried globes standing — they hold their shape until autumn.",
			Desc:    "An ornamental onion carrying a purple sphere of hundreds of tiny star flowers on a bare stem. Bees work a single head for minutes at a time, and the seed head dries into a perfect skeleton.",
			Seasons: []Season{Spring, Summer}, SeedCost: 8, Unlock: 7, Hours: 18,
			Palette: Palette{Stem: "72", Leaf: "78", Bloom: "134", Accent: "141"},
			Art: [StageCount][]string{
				{"  ●  "},
				{"  ¦  "},
				{" ¦│¦ ", "  │  "},
				{"  ◍  ", "  │  ", " ¦│¦ "},
				{" ❋❋❋ ", " ❋❋❋ ", "  │  ", " ¦│¦ ", "  │  "},
			},
		},
		&Species{
			ID: "tigerlily", Common: "Tiger Lily", Latin: "Lilium lancifolium",
			Family: "Liliaceae", Kind: KindBulb, Rarity: Rare,
			Origin: "China, Japan, Korea", Bloom: "mid to late summer",
			Sun: "sun with cool roots", Water: "moderate", Height: "0.9–1.5 m",
			Note:    "The dark bulbils in each leaf axil will grow into new plants if you pot them.",
			Desc:    "Orange, heavily spotted flowers with petals curled right back and long, dangling anthers. Grown as a food crop in parts of East Asia for its starchy bulbs, and famously tolerant of neglect.",
			Seasons: []Season{Summer}, SeedCost: 9, Unlock: 10, Hours: 19,
			Palette: Palette{Stem: "71", Leaf: "77", Bloom: "208", Accent: "88"},
			Art: [StageCount][]string{
				{"  ●  "},
				{"  ϑ  "},
				{" ζ│ζ ", "  │  "},
				{"  ◍  ", " ζ│ζ ", "  │  "},
				{" ╲✿╱ ", " ζ│ζ ", " ζ│ζ ", "  │  "},
			},
		},
		&Species{
			ID: "morningglory", Common: "Morning Glory", Latin: "Ipomoea purpurea",
			Family: "Convolvulaceae", Kind: KindVine, Rarity: Common,
			Origin: "Mexico and Central America", Bloom: "summer to early autumn",
			Sun: "full sun", Water: "moderate", Height: "2–3 m of climb",
			Note:    "Soak the seed overnight and give it string to twine up before it sprawls.",
			Desc:    "A twining annual whose trumpets open at first light and are spent by afternoon. The vine finds its support by circling — a shoot tip sweeps a slow circle in the air until it touches something to grip.",
			Seasons: []Season{Summer}, SeedCost: 4, Unlock: 2, Hours: 15,
			Palette: Palette{Stem: "71", Leaf: "77", Bloom: "62", Accent: "255"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ϑ╱  ", " ╱   "},
				{" ◦╱ϑ ", " ╱ϑ  ", " │   "},
				{" ✿╱ϑ ", " ╱✿  ", " ϑ╱  ", " ╱   "},
			},
		},
		&Species{
			ID: "sweetpea", Common: "Sweet Pea", Latin: "Lathyrus odoratus",
			Family: "Fabaceae", Kind: KindVine, Rarity: Common,
			Origin: "Sicily and southern Italy", Bloom: "early to midsummer",
			Sun: "full sun", Water: "generous", Height: "1.8–2.5 m of climb",
			Note:    "Pick every flower every day, or the plant sets seed and stops.",
			Desc:    "A climbing annual that holds on with leaf tendrils and scents a whole garden. Victorian breeder Henry Eckford turned a modest Sicilian wildflower into the frilled, many-coloured plant we grow now.",
			Seasons: []Season{Spring, Summer}, SeedCost: 4, Unlock: 2, Hours: 16,
			Palette: Palette{Stem: "71", Leaf: "77", Bloom: "176", Accent: "218"},
			Art: [StageCount][]string{
				{"  ●  "},
				{"  ϑ  "},
				{" ϑ│  ", "  │  "},
				{" ◦│ϑ ", " ϑ│  ", "  │  "},
				{" ❀│ϑ ", " ϑ│❀ ", " ❀│ϑ ", "  │  "},
			},
		},
		&Species{
			ID: "wisteria", Common: "Chinese Wisteria", Latin: "Wisteria sinensis",
			Family: "Fabaceae", Kind: KindVine, Rarity: Legendary,
			Origin: "China", Bloom: "late spring, before the leaves",
			Sun: "full sun", Water: "moderate", Height: "9–20 m of climb",
			Note:    "Prune twice a year — in midsummer and again in winter — or it eats the house.",
			Desc:    "A woody climber hung with metre-long trails of scented lilac pea flowers. It twines counter-clockwise, unlike its Japanese cousin, and specimens over a century old are still going strong.",
			Seasons: []Season{Spring}, SeedCost: 18, Unlock: 22, Hours: 20,
			Palette: Palette{Stem: "58", Leaf: "71", Bloom: "140", Accent: "183"},
			Art: [StageCount][]string{
				{"  ●  "},
				{"  ϑ  "},
				{" ϑ│  ", "  │  "},
				{" ◦│◦ ", " ϑ│ϑ ", "  │  "},
				{"╾┬──┬╼", " ❋  ❋ ", " ❋  ❋ ", "  ❋❋  "},
			},
		},
		&Species{
			ID: "clematis", Common: "Italian Clematis", Latin: "Clematis viticella",
			Family: "Ranunculaceae", Kind: KindVine, Rarity: Rare,
			Origin: "southern Europe", Bloom: "midsummer to early autumn",
			Sun: "head in sun, roots in shade", Water: "moderate", Height: "3–4 m of climb",
			Note:    "Cut this group right back to 30 cm in late winter; it flowers on new wood.",
			Desc:    "A slender climber that hangs its nodding flowers outward from the support. Unlike most climbers it grips with twisting leaf stalks rather than tendrils, and it shrugs off the wilt that plagues larger-flowered hybrids.",
			Seasons: []Season{Summer, Autumn}, SeedCost: 10, Unlock: 12, Hours: 19,
			Palette: Palette{Stem: "58", Leaf: "71", Bloom: "127", Accent: "176"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ϑ│  ", "  │  "},
				{" ◦│ϑ ", " ϑ│  ", "  │  "},
				{" ✾│ϑ ", " ϑ│✾ ", " ✾│ϑ ", "  │  "},
			},
		},
		&Species{
			ID: "nasturtium", Common: "Nasturtium", Latin: "Tropaeolum majus",
			Family: "Tropaeolaceae", Kind: KindVine, Rarity: Common,
			Origin: "the Andes of Peru and Bolivia", Bloom: "summer to frost",
			Sun: "full sun", Water: "low", Height: "trails 1–2 m",
			Note:    "Feed it and you get leaves; starve it and you get flowers.",
			Desc:    "Round, water-repellent leaves and spurred flowers in hot colours, every part of it edible with a peppery, watercress bite. Gardeners plant it as a sacrificial trap for blackfly.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 3, Unlock: 0, Hours: 14,
			Palette: Palette{Stem: "71", Leaf: "78", Bloom: "202", Accent: "220"},
			Art: [StageCount][]string{
				{"  ●  "},
				{"  ϑ  "},
				{" ◠ ◠ ", "  │  "},
				{" ◠◦◠ ", " ◠ ◠ ", "  │  "},
				{" ◠❀◠ ", " ❀◠◠ ", " ◠ ◠❀", "  ╲│╱"},
			},
		},
		&Species{
			ID: "honeysuckle", Common: "Common Honeysuckle", Latin: "Lonicera periclymenum",
			Family: "Caprifoliaceae", Kind: KindVine, Rarity: Uncommon,
			Origin: "Europe and North Africa", Bloom: "midsummer, scented at dusk",
			Sun: "sun or part shade", Water: "moderate", Height: "4–7 m of climb",
			Note:    "The scent peaks after dark; plant it where you sit on summer evenings.",
			Desc:    "A hedgerow twiner whose long-tubed flowers open cream and age to gold, releasing their scent at dusk for night-flying hawk moths. Red berries follow and the birds take them quickly.",
			Seasons: []Season{Summer}, SeedCost: 7, Unlock: 6, Hours: 18,
			Palette: Palette{Stem: "58", Leaf: "71", Bloom: "223", Accent: "203"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ϑ│  ", "  │  "},
				{" ◦│ϑ ", " ϑ│  ", "  │  "},
				{" ✽│ϑ ", " ϑ│✽ ", " ✽│●ϑ", "  │  "},
			},
		},
	)
}
