package main

// The kitchen garden: things you can eat, from the fastest radish to the
// slowest pumpkin.
func init() {
	register(
		&Species{
			ID: "tomato", Common: "Tomato", Latin: "Solanum lycopersicum",
			Family: "Solanaceae", Kind: KindEdible, Rarity: Common,
			Origin: "western South America", Bloom: "summer, yellow and self-fertile",
			Sun: "full sun", Water: "deep and regular", Height: "1–2 m",
			Note:    "Water evenly — a dry spell followed by a flood splits the fruit.",
			Desc:    "Domesticated in Mesoamerica and treated with suspicion in Europe for two centuries because of its nightshade relatives. The fruit is botanically a berry; a bumblebee's buzz shakes pollen loose from the flower.",
			Seasons: []Season{Spring, Summer}, SeedCost: 4, Unlock: 1, Hours: 17,
			Palette: Palette{Stem: "65", Leaf: "71", Bloom: "220", Accent: "196"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" ε❁з ", " ε│з ", "  │  "},
				{" ε●з ", " ●│ε ", " ε│● ", " ╲│╱ "},
			},
		},
		&Species{
			ID: "chilli", Common: "Chilli Pepper", Latin: "Capsicum annuum",
			Family: "Solanaceae", Kind: KindEdible, Rarity: Common,
			Origin: "Mexico and Central America", Bloom: "summer",
			Sun: "full sun and heat", Water: "moderate", Height: "40–90 cm",
			Note:    "Slight drought stress once the fruit sets makes the heat sharper.",
			Desc:    "Capsaicin, the compound that burns, binds to the receptor that detects heat — birds lack that receptor, so they eat the fruit freely and spread the seed. One species covers everything from bell peppers to cayenne.",
			Seasons: []Season{Summer}, SeedCost: 4, Unlock: 2, Hours: 17,
			Palette: Palette{Stem: "65", Leaf: "71", Bloom: "255", Accent: "202"},
			Glyphs:  map[rune]glyphClass{'▼': clAccent},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" ε❁з ", " ε│з ", "  │  "},
				{" ε▼з ", " ▼│ε ", " ε│▼ ", "  │  "},
			},
		},
		&Species{
			ID: "carrot", Common: "Carrot", Latin: "Daucus carota subsp. sativus",
			Family: "Apiaceae", Kind: KindEdible, Rarity: Common,
			Origin: "Persia and Central Asia", Bloom: "second year, a white umbel",
			Sun: "full sun", Water: "even moisture", Height: "30 cm of leaf",
			Note:    "Sow thinly straight into the ground; forked roots come from transplanting.",
			Desc:    "Originally purple and yellow; the familiar orange root was selected by Dutch growers in the seventeenth century. The pigment is beta-carotene, which the body converts to vitamin A.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 2, Unlock: 0, Hours: 14,
			Palette: Palette{Stem: "71", Leaf: "78", Bloom: "255", Accent: "208"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ~  "},
				{" ~│~ "},
				{" ~~~ ", " ~│~ "},
				{" ~~~ ", " ~~~ ", " ╲│╱ ", "  ▼  "},
			},
		},
		&Species{
			ID: "radish", Common: "Radish", Latin: "Raphanus sativus",
			Family: "Brassicaceae", Kind: KindEdible, Rarity: Common,
			Origin: "Southeast and Central Asia", Bloom: "quickly, if you let it bolt",
			Sun: "sun to light shade", Water: "steady", Height: "15–25 cm",
			Note:    "The fastest thing in the garden: sow it between slower crops.",
			Desc:    "Ready in as little as three weeks, which makes it the traditional crop for impatient children. Heat and dryness make roots woody and fiercely hot; a steady, cool, damp run keeps them crisp.",
			Seasons: []Season{Spring, Autumn}, SeedCost: 2, Unlock: 0, Hours: 12,
			Palette: Palette{Stem: "71", Leaf: "77", Bloom: "255", Accent: "197"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" εзε "},
				{" εзε ", " ╲│╱ "},
				{" εзεз ", " ε╲│╱з", "   ●  "},
			},
		},
		&Species{
			ID: "lettuce", Common: "Lettuce", Latin: "Lactuca sativa",
			Family: "Asteraceae", Kind: KindEdible, Rarity: Common,
			Origin: "Egypt, from wild lettuce", Bloom: "when it bolts in heat",
			Sun: "sun, shade in high summer", Water: "steady moisture", Height: "20–30 cm",
			Note:    "Pick outer leaves and leave the heart: one plant can feed you for weeks.",
			Desc:    "First grown by the ancient Egyptians for the oil in its seed. Bolting turns the sap bitter with lactucarium, the milky latex that gives the genus its name.",
			Seasons: []Season{Spring, Autumn}, SeedCost: 2, Unlock: 0, Hours: 13,
			Palette: Palette{Stem: "71", Leaf: "114", Bloom: "228", Accent: "155"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" εзε "},
				{" εзεз ", " ╲│╱  "},
				{"εзεзε ", " εзεз ", " ╲│╱  "},
			},
		},
		&Species{
			ID: "pea", Common: "Garden Pea", Latin: "Pisum sativum",
			Family: "Fabaceae", Kind: KindEdible, Rarity: Common,
			Origin: "the Near East and Mediterranean", Bloom: "spring, white and self-pollinating",
			Sun: "full sun", Water: "moderate", Height: "1–2 m of climb",
			Note:    "Give the tendrils netting early; a sprawling pea is a slug's picnic.",
			Desc:    "The plant Gregor Mendel used in the monastery garden experiments that founded genetics — chosen because peas self-pollinate and show clean either-or traits. Nitrogen-fixing roots leave the soil richer than they found it.",
			Seasons: []Season{Spring}, SeedCost: 3, Unlock: 0, Hours: 15,
			Palette: Palette{Stem: "71", Leaf: "77", Bloom: "255", Accent: "119"},
			Art: [StageCount][]string{
				{"  ●  "},
				{"  ϑ  "},
				{" ϑ│  ", "  │  "},
				{" ❁│ϑ ", " ϑ│  ", "  │  "},
				{" ▰│ϑ ", " ϑ│▰ ", " ▰│ϑ ", "  │  "},
			},
		},
		&Species{
			ID: "broadbean", Common: "Broad Bean", Latin: "Vicia faba",
			Family: "Fabaceae", Kind: KindEdible, Rarity: Common,
			Origin: "the Near East, farmed since the Neolithic", Bloom: "spring, black-blotched white",
			Sun: "full sun", Water: "moderate", Height: "0.9–1.5 m",
			Note:    "Pinch out the top once pods set — blackfly always go for the soft tip.",
			Desc:    "One of the oldest crops in cultivation, hardy enough to sow in late autumn for an early summer crop. The scented flowers are a magnet for bumblebees, which sometimes bite through the base to steal nectar.",
			Seasons: []Season{Winter, Spring}, SeedCost: 3, Unlock: 1, Hours: 15,
			Palette: Palette{Stem: "71", Leaf: "108", Bloom: "255", Accent: "119"},
			Art: [StageCount][]string{
				{"  ●  "},
				{"  ϑ  "},
				{" ε│з ", "  │  "},
				{" ε❁з ", " ε│з ", "  │  "},
				{" ε▰з ", " ▰│ε ", " ε│▰ ", "  │  "},
			},
		},
		&Species{
			ID: "pumpkin", Common: "Pumpkin", Latin: "Cucurbita pepo",
			Family: "Cucurbitaceae", Kind: KindEdible, Rarity: Uncommon,
			Origin: "Mexico and the southern United States", Bloom: "summer, huge and orange",
			Sun: "full sun", Water: "thirsty; soak the roots, not the leaves", Height: "trails 3–5 m",
			Note:    "Slide a tile under a swelling fruit to keep it off damp ground.",
			Desc:    "One of the oldest domesticated plants in the Americas, with seeds found in Mexican caves dating back roughly ten thousand years. Male flowers open first; only the female ones, with a tiny fruit behind the petals, become pumpkins.",
			Seasons: []Season{Summer, Autumn}, SeedCost: 6, Unlock: 4, Hours: 19,
			Palette: Palette{Stem: "65", Leaf: "71", Bloom: "220", Accent: "208"},
			Glyphs:  map[rune]glyphClass{'◍': clAccent},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ◠│◠ ", "  │  "},
				{" ◠❀◠ ", " ◠ ◠ ", "  │  "},
				{" ◠ ◠◠", "◠ ◍ ◠", " ╲│╱ ", "  │  "},
			},
		},
		&Species{
			ID: "sweetcorn", Common: "Sweetcorn", Latin: "Zea mays",
			Family: "Poaceae", Kind: KindEdible, Rarity: Uncommon,
			Origin: "southern Mexico", Bloom: "midsummer tassels",
			Sun: "full sun", Water: "generous while the cobs fill", Height: "1.5–2.5 m",
			Note:    "Plant in a block, not a row — the wind has to carry pollen between plants.",
			Desc:    "Bred from the grass teosinte over thousands of years of Mesoamerican selection. Each silk thread runs to one potential kernel, so a patchy cob means patchy pollination.",
			Seasons: []Season{Summer}, SeedCost: 6, Unlock: 5, Hours: 19,
			Palette: Palette{Stem: "71", Leaf: "77", Bloom: "223", Accent: "220"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ¦  "},
				{" ╲│╱ ", "  │  "},
				{" ╲│╱ ", " ╲│╱ ", "  │  "},
				{" ~~~ ", " ╲│╱ ", " ╲▰╱ ", " ╲│╱ ", "  │  "},
			},
		},
		&Species{
			ID: "strawberry", Common: "Garden Strawberry", Latin: "Fragaria × ananassa",
			Family: "Rosaceae", Kind: KindEdible, Rarity: Common,
			Origin: "a Breton garden hybrid of Chilean and Virginian species", Bloom: "late spring",
			Sun: "full sun", Water: "even moisture", Height: "20–30 cm",
			Note:    "Peg the runners into pots in summer for free plants next year.",
			Desc:    "The fruit is not a berry: the fleshy part is swollen receptacle and the true fruits are the pips on the outside. Every modern variety descends from an accidental eighteenth-century cross made in Brittany.",
			Seasons: []Season{Spring, Summer}, SeedCost: 5, Unlock: 3, Hours: 16,
			Palette: Palette{Stem: "71", Leaf: "77", Bloom: "255", Accent: "197"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" εзε "},
				{" ε❁з ", " ╲│╱ "},
				{" εзε ", " ●з● ", " ╲│╱ "},
			},
		},
		&Species{
			ID: "garlic", Common: "Garlic", Latin: "Allium sativum",
			Family: "Amaryllidaceae", Kind: KindEdible, Rarity: Common,
			Origin: "Central Asia", Bloom: "a curling scape in early summer",
			Sun: "full sun", Water: "moderate, dry as it ripens", Height: "40–70 cm",
			Note:    "Plant cloves in autumn: garlic needs a cold spell to split into a head.",
			Desc:    "Cut or crushed cloves release allicin, a defence compound the plant makes only when its cells are damaged. Hardneck varieties send up a looping flower scape which, snapped off, thickens the bulb and makes good eating.",
			Seasons: []Season{Autumn, Winter, Spring}, SeedCost: 4, Unlock: 2, Hours: 16,
			Palette: Palette{Stem: "72", Leaf: "108", Bloom: "255", Accent: "253"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ¦  "},
				{" ¦│¦ "},
				{" ¦│¦ ", " ¦│¦ "},
				{"  ╭❀ ", " ¦│  ", " ¦│¦ ", " ╲│╱ "},
			},
		},
		&Species{
			ID: "beetroot", Common: "Beetroot", Latin: "Beta vulgaris",
			Family: "Amaranthaceae", Kind: KindEdible, Rarity: Common,
			Origin: "coastal Europe and North Africa", Bloom: "second year",
			Sun: "full sun", Water: "steady", Height: "30–40 cm of leaf",
			Note:    "Each wrinkled 'seed' is a cluster, so thin the seedlings ruthlessly.",
			Desc:    "Bred from sea beet, the same species as chard and sugar beet. The deep colour comes from betalain pigments rather than the anthocyanins that redden most plants.",
			Seasons: []Season{Spring, Summer, Autumn}, SeedCost: 3, Unlock: 1, Hours: 15,
			Palette: Palette{Stem: "161", Leaf: "71", Bloom: "228", Accent: "125"},
			Art: [StageCount][]string{
				{"  ·  "},
				{"  ϑ  "},
				{" ε│з "},
				{" ε│з ", " ε│з "},
				{" εзε ", "ε╲│╱з", "  ●  "},
			},
		},
	)
}
